### PR TITLE
Updates gems and adds a new service

### PR DESCRIPTION
**Pull request by carsonb**
I went to run this and ran across some errors due to older versions of gems not installing on my system, so I updated the Gemfile.lock.

Also included is a new provider to the list, icanhazip.com.

### CODE REVIEW

**Comment by dreamins** [comment]
I removed the icanhazip. No idea who those people are.

**Comment by dreamins** [comment]
P.S. Sorry for horrendously late response, it got lost somehow, I blame my mail filters. Thanks for request.

**Comment by carsonb** [comment]
No worries on the reply latency :-)

I realize it wasn't really fair to sneak in a provider while fixing gem versions. icanhazip is one of a few services provided by Major Hayden, you can read more here: https://major.io/icanhazip-com-faq. Source is here: https://github.com/major/icanhaz

**Comment by dreamins** [comment]
Looks legit. Adding.

Thanks.

**Pull request merged**
